# Generated by Django 4.2.5 on 2023-09-15 17:06

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=255)),
                ('balance', models.PositiveBigIntegerField(default=0)),
                ('currency', models.CharField(choices=[('EUR', 'euro'), ('USD', 'U.S. dollar'), ('IRR', 'Iranian Rial')], default='IRR', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveBigIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_from', to='api.account', verbose_name='from client')),
                ('to_account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_to', to='api.account', verbose_name='to client')),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enteries', to='api.account', verbose_name='client name')),
            ],
        ),
    ]
